import Typography from "@atom/typography/page"
import "./globals.css"
import { Inika, Roboto } from "next/font/google"

const inika = Inika({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inika",
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-roboto",
})

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen container mx-auto ${inika.variable} ${roboto.variable}`}>
        <header>
          <div className="flex content-center items-center">
            <img src="./images/orange.svg" />
            <Typography variant="h1" className="header-title text-xl">
              rganic shop
            </Typography>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
